### ISSUE TITLE
Could not read varint in lib/index.js

### ISSUE THREAD

**Issue by imjoshin** [HearthSim/npm-deckstrings#2]
Decoding certain deck codes fail to process, such as this one:

`AAECAa0GHqEE1Qq0AvsM5MICysMCCfYHnALovwKQ0wLqvwKDuwK+yAKhrAKS tALYuwLTCvDPAtcK0cEC2MEC+wGKAe0F5QS1uwLyDJcCpQkA=`

Here is the error I am receiving:
`RangeError: Could not decode varint
    at Object.read [as decode] (/dir/node_modules/deckstrings/lib/index.js:48:13)
    at BufferReader.nextVarint (/dir/node_modules/deckstrings/lib/index.js:181:27)
    at Object.decode (/dir/node_modules/deckstrings/lib/index.js:287:36)
    at /dir/bot.js:89:28
    at Array.forEach (native)
    at DiscordClient.details (/dir/bot.js:87:10)
    at DiscordClient.EventEmitter.emit (events.js:106:17)
    at DiscordClient.handleWSMessage (/dir/node_modules/discord.io/lib/index.js:1803:11)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.ontext (/dir/node_modules/discord.io/node_modules/ws/lib/WebSocket.js:841:10)
    at /dir/node_modules/discord.io/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/dir/node_modules/discord.io/node_modules/ws/lib/Receiver.js:371:5)
    at /dir/node_modules/discord.io/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/dir/node_modules/discord.io/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.opcodes.1.finish (/dir/node_modules/discord.io/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/dir/node_modules/discord.io/node_modules/ws/lib/Receiver.js:499:31)`

**Comment by beheh** [comment]
That deck code does not appear to be valid, since I can't get Hearthstone to import it. It's probably malformed.

**Comment by beheh** [comment]
I'll dig into it a bit more just in case, but do let me know if it should work for you in Hearthstone.

**Comment by imjoshin** [comment]
Weird, looks like you're right. I took it from [here](https://disguisedtoast.com/meta_decks/79-highlander-priest) and it works fine in a php decoder I have. If it isn't valid to Hearthstone, there's no bug here. Sorry about that 😄
